[monitor]
10.1.1.242

[primary]
10.1.1.242

[standby]
10.1.1.23
10.1.1.242

[haproxy]
10.1.1.242

[pgbouncer]
10.1.1.242

[database:children]
primary
standby

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
