[monitor]
10.1.1.249

[primary]
10.1.1.183

[standby]
10.1.1.169
10.1.1.128

[haproxy]
10.1.1.36

[pgbouncer]
10.1.1.36

[database:children]
primary
standby

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
